version: '3.1'

services:
  spatial-db:
    image: mysql:5.7.22
    environment:
      - MYSQL_DATABASE=biodiversity
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./database/:/var/lib/mysql/
  biodiversity-api:
    image: g00glen00b/biodiversity-api:1.0.2
    depends_on:
      - spatial-db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=spatial-db
      - DATABASE_PORT=3306
      - SPRING_DATASOURCE_URL=jdbc:mysql://spatial-db/biodiversity?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USER}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - API_GBIF_LOCATION_PATTERN=file:/datasets/*/occurrence.txt
      - SPRING_BATCH_JOB_ENABLED=true
    volumes:
      - ./datasets/:/datasets/
