version: '3.1'

services:
  spatial-db:
    image: mysql:5.7.22
    environment:
      - MYSQL_DATABASE=biodiversity
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 3306:3306
